# Generated by Django 2.2.6 on 2019-10-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.EmailField(max_length=254)),
                ('service_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
